#Each new term in the Fibonacci sequence is generated by adding the previous two terms.
# By starting with 1 and 2, the first 10 terms will be:

#1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...

#By considering the terms in the Fibonacci sequence whose values do not exceed four million,
# find the sum of the even-valued terms.


anterior = 0
atual = 1
sumOfEven = 0

while(atual<=4000000):
    aux = atual
    atual = anterior + aux
    anterior = aux


    if (atual % 2 == 0):
        sumOfEven += atual

    print(f"{atual}")
print(f"{sumOfEven}")